/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export enum PaymentMethodReferenceTag {
    Id = "id",
}

export class PaymentMethodReference extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: ".tag" })
    dotTag: PaymentMethodReferenceTag;

    /**
     * Payment ID of the saved Bolt Payment method.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;
}
