/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Cart } from "./cart";
import { PaymentMethodReference } from "./paymentmethodreference";
import { Expose, Type } from "class-transformer";

export class PaymentInitializeRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cart" })
    @Type(() => Cart)
    cart: Cart;

    @SpeakeasyMetadata()
    @Expose({ name: "payment_method" })
    @Type(() => PaymentMethodReference)
    paymentMethod: PaymentMethodReference;
}
