/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class TransactionUpdateRequestOrderCart extends SpeakeasyBase {
    /**
     * A shopper-facing identifier corresponding to the order reference associated with this transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "display_id" })
    displayId?: string;
}

export class TransactionUpdateRequestOrder extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cart" })
    @Type(() => TransactionUpdateRequestOrderCart)
    cart?: TransactionUpdateRequestOrderCart;
}

export class TransactionUpdateRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "order" })
    @Type(() => TransactionUpdateRequestOrder)
    order?: TransactionUpdateRequestOrder;
}
