/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class TransactionUpdateRequestCart extends SpeakeasyBase {
    /**
     * A shopper-facing identifier corresponding to the order reference associated with this transaction.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "display_id" })
    displayId?: string;
}

export class Order extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "cart" })
    @Type(() => TransactionUpdateRequestCart)
    cart?: TransactionUpdateRequestCart;
}

export class TransactionUpdateRequest extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "order" })
    @Type(() => Order)
    order?: Order;
}
