/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { PaymentsGuest } from "./paymentsguest";
import { PaymentsLoggedIn } from "./paymentsloggedin";
import { SDKConfiguration } from "./sdk";

export class Payments {
    public guest: PaymentsGuest;
    public loggedIn: PaymentsLoggedIn;
    private sdkConfiguration: SDKConfiguration;

    constructor(sdkConfig: SDKConfiguration) {
        this.sdkConfiguration = sdkConfig;
        this.guest = new PaymentsGuest(this.sdkConfiguration);
        this.loggedIn = new PaymentsLoggedIn(this.sdkConfiguration);
    }
}
